spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
currency:
  http:
    client:
      config:
        connectionTimeout: 1000
        readTimeout: 1000
        uri: http://api.nbp.pl/api/exchangerates/tables/A?format=json
