spring:
  h2.console:
    enabled: false
  datasource:
    url: jdbc:h2:file:./exchratenbp
  jpa.hibernate:
    ddl-auto: update

currency:
  http:
    client:
      config:
        connectionTimeout: 1000
        readTimeout: 1000
        uri: http://api.nbp.pl/api/exchangerates/tables/A?format=json
